### PR TITLE
docs: fix keptn task example link

### PR DESCRIPTION
**Pull request by shardulsrivastava**
Signed-off-by: Shardul Srivastava <shardul.srivastava007@gmail.com>

Fix the Ketpn `KeptnTaskDefinition` link. fixes https://github.com/keptn/lifecycle-toolkit/issues/679

### CODE REVIEW

**Comment by agardnerIT** [comment]
LGTM (but I'm not a reviewer :) )

**Comment by mowies** [comment]
hey @shardulsrivastava !
please file you PR against keptn/lifecycle-toolkit. we have a `docs` folder over there now which is used a source for this repo

**Comment by shardulsrivastava** [comment]
@mowies I checked on the `keptn/lifecycle-toolkit` repo, and there is no error in the document in this [repo](https://github.com/keptn/lifecycle-toolkit/blob/main/docs/content/en/docs/concepts/tasks/_index.md?plain=1#L71) , in fact this line is missing, while I can see the line in the actual doc and it points to the wrong url.

Perhaps this [page](https://lifecycle.keptn.sh/docs/concepts/tasks/)  is still being served from `lifecycle-toolkit-docs`.

**Review by mowies — APPROVED** [review]

**Comment by mowies** [comment]
All pages are served from  `keptn/lifecycle-toolkit-docs` but the development version of the docs gets pushed there from `keptn/lifecycle-toolkit`.
The only issue is, that the development version gets pushed to the `dev` version in the KLT docs and not the main version.
So you're right, we can just merge this and fix the link.

**Pull request merged**
